In [ ]:
import numpy as np

x = np.array(range(6))
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
! pip3 install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 51.1 MB/s eta 0:00:0000:0100:01


In [ ]:
x.shape

(6,)

In [ ]:
y=np.array(range(6)).reshape(2,3)

In [ ]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y.ndim

2

In [ ]:
arr3=np.array(range(10))
arr3.reshape(2,5)
arr3.ndim

1

In [ ]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array(range(10)).reshape(2,5)
arr.ndim

2

In [ ]:
from sklearn.datasets import load_diabetes 

diabetes = load_diabetes()

In [ ]:
! pip3 install sklearn

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 45.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 38.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 31.2 MB/s eta 0:00:0000:0100:01
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1304 sha256=324265431944f7f066cb713b3b19ffa0959bc11b457754cd867a59419e8cdb9e
  Stored in directory: /home/jovyan/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [ ]:
type(diabetes)

sklearn.utils.Bunch

In [ ]:
data=diabetes.data
print(data.shape, data.ndim)

(442, 10) 2


In [ ]:
arr2 = np.array(range(12)).reshape(3,4)
arr2.ndim

2